### ISSUE TITLE
Mistake and missings in readme

### ISSUE THREAD

**Issue by NikoVonLas** [smartcatai/SmartCAT-API#4]
`use SmartCAT\API\SmartCAT;`
But namespace now is:
`use SmartCat\Client\SmartCat;`
And namespaces missing in other examples where uses any models.
Also how use ` $smartcat->getProjectManager()->projectCreateProject($prjCreate);`?
Readme missing example for this method.
Im trying like that:
```
$prjCreate = new CreateProjectModel();
$prjCreate->setName('Name');
$projectSC = $smartcat->getProjectManager()->projectCreateProject($prjCreate);
```
And get 400 error.
In comments for method @throws \Exception
But it throws: \Http\Client\Common\Exception\ClientErrorException

**Comment by NikoVonLas** [comment]
When i test request in https://smartcat.ai/api/methods/#/
POST /api/integration/v1/project/create
```
{
  "name": "TESTING API",
  "sourceLanguage": "en",
  "targetLanguages": [
    "uk"
  ]
}
```
I get 415 error, whats wrong?

**Comment by NikoVonLas** [comment]
Im find problem.

When i try to create project with you lib i get thars response from server:
```
Error processing request. Correlation id: 589d9933-c462-4b3c-8903-3a3202b2e30a
Error parsing JSON. Content:
{\"name\":\"Test_Freedom\",\"sourceLanguage\":\"en\",\"targetLanguages\":[\"uk\"]}
```

I think you server just add backslashes to double quotes in json. 
I check that by change double quotes to single quotes and get response without backslashes: 
```
Error processing request. Correlation id: 6135ebb3-4760-441f-88d6-39180c480251
Error parsing JSON. Content:
{'name':'Freedom test','sourceLanguage':'en','targetLanguages':['ru']}
```

As per the [rfc7159](http://www.faqs.org/rfcs/rfc7159.html) JSON Standard(used in php json_encode/json_decode), in json always use not escaped double quotes for string. And of course json_decode cant parse this.

**Comment by Medic84** [comment]
No, your problem is in incorrect project. For the project required fields is: **name, description, sourceLanguage, targetLanguages, assignToVendor**
In this case, correctly to write:
```
$prjCreate = new CreateProjectModel();
$prjCreate->setName('Name');
$prjCreate->setDescription('Test');
$prjCreate->setSourceLanguage( 'en' );
$prjCreate->setTargetLanguages(['ru']);
$prjCreate->setAssignToVendor(false);
$projectSC = $smartcat->getProjectManager()->projectCreateProject($prjCreate);
```

**Comment by Medic84** [comment]
Namespace errors in readme file we will correct in few days

**Comment by NikoVonLas** [comment]
Thanks. Please update swagger docs. In docs no one field is required.
